### ISSUE TITLE
interactions download error occurred

### ISSUE THREAD

**Issue by bhupeshmoudgil** [newvoicemedia/vcc-node-code-snippets#20]
:interaction-content-download usr$ node app.js --start 2020-05-01T00:00:00Z --end 2020-05-31T23:59:59Z
Downloading files to '/vcc-node-code-snippets-master/downloads'
Searching for interactions between '2020-05-01T00:00:00Z' - '2020-05-31T23:59:59Z'

Getting page 1
Getting token from server
Search failed Number of days between 'start' date and 'end' date can't be greater than 7 days Bad Request
Error occurred
 
 
i need to be able to download atleast a month, 7 days is way too low

**Comment by dvelluto** [comment]
Hi @bhupeshmoudgil , thanks for reaching out. I'm sorry but the requested feature is out of the scope of this repository, which provides examples of usages for our API. As stated in the public documentations, the limit is 7 days by design. [Link to Documentation](https://docs-vcc.atlassian.net/wiki/spaces/VCCA/pages/3567190597/Search+for+interactions)

To download a month of interactions I can suggest you to loop the code 4 times in order to cover the 4 weeks of the month.
